# Generated by Django 4.1.2 on 2022-10-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Kategori",
            },
        ),
        migrations.CreateModel(
            name="Circle_produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("deskripsi", models.TextField()),
                ("jumlah", models.IntegerField()),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produk.kategori",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produk",
            },
        ),
    ]
